#!/bin/sh

normal_file="normal"
secret_file="secret"
git_user="Test User"
git_email="test.user@example.com"

if [ -d secret_repo ]; then
  rm -rf secret_repo
fi

git init secret_repo
cd secret_repo

echo "Some normal data" >$normal_file
git add $normal_file
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-01 00:00:00' git commit -m "Normal data started"

echo "Some more normal data" >>$normal_file
git add $normal_file
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-01 00:01:00' git commit -m "Normal data added"

echo "kewlhaxxor:sUpAsEcRiTpA55w0rD@example.com" >$secret_file
git add $secret_file
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-01 00:02:00' git commit -m "Test data added"

git rm $secret_file
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-01 00:02:05' git commit -m "Opps. Let's revert credentials until someone finds them"

echo "Even more normal data" >>$normal_file
git add $normal_file
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-01 00:03:00' git commit -m "Still adding normal data"

cd ../
