#!/bin/sh

git_user="Test User"
git_email="test.user@example.com"

if [ -d test_repo ]; then
  rm -rf test_repo
fi

git init test_repo
cd test_repo

mkdir src
echo "Some very cool sources here" > src/file1
git add src/file1
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-01 00:00:00' git commit -m "Cool project started"

echo "More cool sources go" >> src/file1
git add src/file1
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-02 00:00:00' git commit -m "Cool project continue"

echo "Line with a tipo" >> src/file1
git add src/file1
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-03 00:00:00' git commit -m "Work goes on"

mkdir Src
echo "We need more sources" > Src/file2
git add Src/file2
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-04 00:00:00' git commit -m "More sources added"

git branch feature
git checkout master

mkdir secrets
echo "Big secret" > secrets/big_secret
git add secrets/big_secret
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-05 00:00:00' git commit -m "Big Secret added"

sed -i 's/tipo/typo/g' src/file1
git add src/file1
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-06 00:00:00' git commit -m "Typo fixed"
commit_id=`git rev-parse HEAD | cut -c1-8`

git rm secrets/big_secret
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-05 00:00:00' git commit -m "Big Secret removed"

git checkout feature

echo "Here goes code for cool feature" >> Src/file2
git add Src/file2
GIT_AUTHOR_NAME="${git_user}" GIT_AUTHOR_EMAIL="${git_email}" faketime '2017-01-04 12:00:00' git commit -m "Cool feature started"

git cherry-pick $commit_id
GIT_COMMITER_NAME="${git_user}" GIT_COMMITER_EMAIL="${git_email}" faketime '2017-01-04 12:30:00' git commit --amend -m "Typo fixed (cp ${commit_id} from master)"

git checkout master


cd ../
